services:
  - type: web
    name: eng-vis-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:8000 --log-level info
    autoDeploy: false # Disable auto-deploy for backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Set manually in Render dashboard

  - type: web
    runtime: static
    name: eng-vis-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeploy: true # Enable auto-deploy for frontend (this is default, but being explicit)
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.js
        name: Content-Type
        value: application/javascript
    envVars:
      - key: VITE_API_BASE_URL
        value: https://eng-vis-backend.onrender.com # Update after backend is deployed
