services:
  - type: web
    name: eng-vis-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:8000 --log-level info
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Set manually in Render dashboard

  - type: web
    runtime: static
    name: eng-vis-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
